7. Django framework/week 04 final project/bank_management/mamar_bank/account/urls.py
from django.urls import path
from account.views import UserRegistrationView, UserLoginView, UserLogoutView, UserUpdateView

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name= 'register'),
    path('login/', UserLoginView.as_view(), name= 'login'),
    path('logout/', UserLogoutView.as_view(), name= 'logout'),
    path('update/', UserUpdateView.as_view(), name= 'update'),
]

7. Django framework/week 04 final project/bank_management/mamar_bank/core_app/urls.py
from django.urls import path
from core_app.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'), 
]

7. Django framework/week 04 final project/bank_management/mamar_bank/mamar_bank/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core_app.urls')),
    path('account/', include('account.urls')),
    path('transactions_app/', include('transactions_app.urls')),
]

7. Django framework/week 04 final project/bank_management/mamar_bank/transactions_app/urls.py
from django.urls import path
from transactions_app.views import DepositMoneyView, WithdrawMonyView,LoanRequestView,  TransactionReportView, PayLonaView, LonaListView, TransferMoneyView, ChangePassword

app_name = 'transactions_app'
urlpatterns = [
    path('deposit/', DepositMoneyView.as_view(), name = 'deposit'),
    path('withdrawal/', WithdrawMonyView.as_view(), name = 'withdrawal'),
    path('loan_request/', LoanRequestView.as_view(), name = 'loan_request'),
    path('report/', TransactionReportView.as_view(), name = 'transaction_report'),
    path('loans/<int:loan_id>/', PayLonaView.as_view(), name = 'pay_loan'),
    path('loans/', LonaListView.as_view(), name = 'loan_list'),
    path('transfer/', TransferMoneyView.as_view(), name = 'transfer'),
    path('change_pass/', ChangePassword, name = 'change_pass'),
]

7. Django framework/week 04 final project/bank_management/mamar_bank/core_app/models.py
from django.db import models

# Create your models here.

7. Django framework/week 04 final project/bank_management/mamar_bank/core_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

7. Django framework/week 04 final project/bank_management/mamar_bank/core_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.0.1/dist/tailwind.min.css">
    {% block link %}{% endblock link %}
</head>
<body class="bg-indigo-600">
   
    {% include 'navbar.html' %}


    {% block content %}
   
    {% endblock content %}
</body>
</html>

7. Django framework/week 04 final project/bank_management/mamar_bank/core_app/templates/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-white p-6 px-10">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight text-blue-900"><a href="{% url "home" %}">Sonali Bank</a></span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto px-10">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'transactions_app:transaction_report' %}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-900 hover:text-red-900 hover:font-black mr-4">
                Transaction Report
                </a>
                <a href="{% url 'transactions_app:deposit' %}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-900 hover:text-red-900 hover:font-black mr-4">
                    Deposit
                </a>
                <a href="{% url 'transactions_app:withdrawal' %}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-900 hover:text-red-900 hover:font-black mr-4">
                    Withdraw
                </a>
                <a href="{% url 'transactions_app:loan_request' %}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-900 hover:text-red-900 hover:font-black mr-4">
                    Loan Request
                </a>
                <a href="{% url 'transactions_app:transfer' %}" class="block mt-4 lg:inline-block lg:mt-0 text-blue-900 hover:text-red-900 hover:font-black mr-4">
                    Transfer Money
                </a>
            </div>
            <div class="flex w-auto">
                <div class="text-blue-900 my-auto font-black px-5">
                    Welcome, {{ request.user.first_name }} 
                    (balance : {{request.user.account.balance}})
                </div>
                <a href="{% url 'update' %}" class="mx-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-dark hover:bg-red-700 mt-4 lg:mt-0">Profile</a>
                <a href="{% url 'logout' %}" class="mx-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-dark hover:bg-red-700 mt-4 lg:mt-0">Logout</a>
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'login' %}" class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-red-700 mt-4 lg:mt-0">Login</a>
            </div>
            <div>
                <a href="{% url 'register' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a>
            </div>
        {% endif %}
    </div>
</nav>